### ISSUE TITLE
Votes: Split the vote columns: One for the user's votes, a different one for total votes

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1013]
I made a mistake here; having one column that tries to do both is confusing, when there are -10 to +10 votes per person.

Instead, change the current voting widget to show the user's vote count, from -10 to +10. 

Add an additional column that would include the total votes for this measurement; the user's votes, plus the total of the others.

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/73350088-4e993080-4284-11ea-868d-4c7fdd8e5c8b.png)

**Comment by lagerros** [comment]
Hm this will turn into lots of columns, and I feel it will be messy. As a solution, I'd vote for removing the "Prediction" column. It's misleading in cases of multimodals or other weird shapes, and when the shape is more standard the "Input text" column communicates the same information (or better, since it will have no smoothing errors).

**Comment by OAGr** [comment]
I've fine removing the Prediction column.
