### ISSUE TITLE
Only show certified forecaster's predictions in the aggregate, if the certifiedForecaster setting is on.

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#1133]
In communities that require "verified forecasters", only verified forecasters's predictions should be part of the aggregate.

Anyone can make predictions though.

**Comment by RomanGalochkin** [comment]
After some thoughts and code, I understood that this approach is not convenient. The better would not admit to add predictions into a verifiable channel for unverified users. Because there is a small weird logic branch appears when we are getting a bunch of measurements for aggregate and should filter out not verified measurements. Let say I used "isVerified" argument in Measurements Query, then I should return all measurements from unverifiable channels and at the same time, I should return measurements from verifiable channels. It is not complicated to write the code but it is weird. So should we go on using this approach?

**Comment by OAGr** [comment]
It's kind of weird, but I think it's fine. Later on we can add multiple aggregations, instead of changing the aggregation.

A different thing we can do is now have one aggregation bot that only applies to verified communities, and a different one that only applies to nonverified communities. The verified one filters for verified users (which I think itself should just be one line of code). 

We could give these distinct names, like, "Aggregate bot" and "Verified aggregate bot".

**Comment by RomanGalochkin** [comment]
Oh, ok. Will go on with this approach.
