### ISSUE TITLE
Distributions get cut off

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#527]
![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/954d0d61-72cb-4b46-9f5e-67d249815be9)

![image](https://user-images.githubusercontent.com/377065/62899048-d75ff680-bd4e-11e9-89be-dd5b27684a81.png)

Here I specified a distribution with a 90th percentile from 10 to 30. It seems like it's set to cut off all values outside of that range, which is not what is wanted. I don't want it to artificially cut out values unless this is explicitly specified.

**Comment by OAGr** [comment]
I'm going to guess this was caused by this:
https://github.com/foretold-app/foretold/pull/524

**Comment by RomanGalochkin** [comment]
So this means that there are no issues are corresponded with a client code and "log normal distribution" issue (https://github.com/foretold-app/foretold/issues/287) since client just prepares data for instance from 1 to 80 0000 and passes it right into this lib https://www.npmjs.com/package/pdfast (this lib returns KDE from minus to minus number), am I right?

**Comment by OAGr** [comment]
Sorry; 
There still is an issue with #287. The correct way to fix #287 isn't with forcing the sides to be cut off, but instead to use a better/more precise smoothing algorithm,

**Comment by RomanGalochkin** [comment]
So, thanks for comment.
