### ISSUE TITLE
Show non-aggregate bots In the Member, Question, and Prediction Scores.

### ISSUE THREAD

**Issue by OAGr** [foretold-app/foretold#684]
Show results from the competitive measurements made by bots, which should be scored the same as users. If a bot just provided aggregates, there shouldn't be shown at this point.

**Comment by RomanGalochkin** [comment]
In this issue I see two approaches of implementation. The main complexity is that "ChannelMembership" tables does not contain not added members. That means that non-aggregate bots are not within this table.

So here are the next proposals:
1. We create new view which named as "ChannelsMembers" (against the "ChannelMemberships"). This view will return members from "ChannelsMemberships" and members having added measurements. Similar to this SQL:
```
WITH "MembersFromMeasuremrens" AS (SELECT DISTINCT "Measurables"."channelId",
                                                   "Measurements"."agentId"
                                   FROM "Measurables",
                                        "Measurements"
                                   WHERE "Measurements"."measurableId" =
                                         "Measurables"."id"),
     "MembersAsMembers" AS (SELECT "agentId", "channelId"
                            FROM "ChannelMemberships")
SELECT *
FROM "MembersFromMeasuremrens"
UNION
SELECT *
FROM "MembersAsMembers"
``` 
2. We add new "member" into "ChannelMemerships" table every time when somebody tries to add new measurement for instance as a bot. Here we give role as "viewer" and set "methodCreatedBy" as "added_with_new_measurement".
 - But since we have added bots into "ChannelsMemberships" table we should filter it out of client's queries.  
- And this is data. It means we should write migration to add non-aggregate bots as members of channels.

In a word I would prefer the first way. What would you prefer? @OAGr
