### ISSUE TITLE
API for creating and exporting predictions

### ISSUE THREAD

**Issue by brachbach** [foretold-app/foretold#800]
Currently at Ought, we're giving our experiment participants surveys, and we want to predict their responses to ~every question on the survey. Like 20 responses per survey, and like one survey per day. We create the questions through scripts that process the inputs and then ultimately create the survey via the Typeform API. Ultimately, we want to store all of the predictions elsewhere than Foretold (probably Airtable)

I'm thinking about using Foretold for making the predictions, but one reason not to is that it'd be a bit tricky to get the predictions in and out. (TBC there are also other reasons -- probably the most compelling other reason is that these predictions are fairly simple, and I'm not sure that Foretold would add much over a spreadsheet)

In the absence of a public API -- what _would_ be the best way to get the predictions in and out of Foretold? My first thought is to write graphql queries and run them from our scripts directly on Foretold's graphql API (bypassing the Foretold frontend)

**Comment by OAGr** [comment]
Hi Ben,

You can currently access the API here: 
https://api.foretold.io/graphql

Introspection is turned on. Questions are "measurables". Predictions are "measurements" (because there are multiple kinds of predictions). We don't have great docstrings now, can add some if that would be useful.

Do you want multiple people to predict the responses on each of the survey questions? If not, I imagine it may not be worth the effort. If you want them too, and especially if they will leave comments and change their predictions based on information from each other, then it could be more worthwhile. 

I feel like getting the predictions out will be the easy part. The more tricky part will be figuring out the user interface, especially if they aren't using the Foretold UI (and even if they are it may be a bit tricky).

Some questions I'd want to understand before really answering:
1. Can you give some examples of the questions? Are these multiple choice, binary, numeric?
2. What should the interface be like for people to make predictions? If it's not directly in foretold, you could have a bot represent each person, and each bot will get a separate API key.
3. (Repeated from above): Do you want multiple people to predict the responses on each of the survey questions?  Do you want other people in the forecasting community to have the option? (It could be convenient in this case if it were in Foretold, because it would be easier for them to hop in / out.
4. Would you want any scoring method implementations?

Happy to discuss over video or similar.

**Comment by brachbach** [comment]
sweet, thx for sharing the API!

1. Shared some examples with you in a spreadsheet: https://docs.google.com/spreadsheets/d/1B_Fmtm3tFy5pftjZkQm2uWbdOGxmPEdJJktOZeErCws/edit#gid=454503003
2. Foretold UI
3. yeah, multiple predictors for each survey question. I don't think it will be too important to change predictions based on information from each other, though
4. Vaguely seems sort of nice but definitely not that important

**Comment by brachbach** [comment]
TBC, the main thing I'd want out of using Foretold for this would be being able to use the Foretold UI

**Comment by brachbach** [comment]
FYI I'm now feeling pretty happy with my spreadsheet version of this linked above, so not too likely to want to try to use Foretold

(I might feel differently if I expected it to be really extremely easy and smooth)

**Comment by OAGr** [comment]
That makes sense! Foretold will continue to get more smooth, you could check in periodically or so. You can also combine it with Retool for a more customized workflow, but this obviously takes some effort.
